import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
import { GoogleAnalytics } from "./google-analytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare var dataLayer:unknown;
declare var window: unknown;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <title>Irwansyah - Personal Web Site</title>        
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />      
          
        <GoogleAnalytics/>
        
      </head>
      <body className="is-preload">        
        {children}
      </body>
    </html>
  );
}
